context.modules = [
    {   name = libpipewire-module-filter-chain
        args = {
            node.description = "ROG Ally 音效增强"
            filter.graph = {
                nodes = [
                    {
                        type  = lv2
                        name  = eq
                        plugin = "http://gareus.org/oss/lv2/fil4#stereo"
                        control = {
                            "enable" = 1.0
                            "gain"   = 0.0
                            "LSsec"  = 1.0
                            "LSfreq" = 240.0
                            "LSgain" = 3.0
                            "LSq"    = 0.7
                            "sec1"   = 1.0
                            "freq1"  = 3150.0
                            "gain1"  = -3.0
                            "q1"     = 1.0
                            "sec2"   = 0.0
                            "sec3"   = 0.0
                            "sec4"   = 0.0
                            "HSsec"  = 0.0
                            "HighPass" = 0.0
                            "LowPass"  = 0.0
                        }
                    }
                    {
                        type  = lv2
                        name  = multicomp
                        plugin = "urn:zamaudio:ZaMultiCompX2"
                        control = {
                            "xover1"    = 230.0
                            "xover2"    = 3150.0
                            "toggle1"   = 1.0
                            "toggle2"   = 1.0
                            "toggle3"   = 1.0
                            "att1"      = 10.0
                            "att2"      = 10.0
                            "att3"      = 5.0
                            "rel1"      = 55.0
                            "rel2"      = 60.0
                            "rel3"      = 40.0
                            "kn1"       = 3.0
                            "kn2"       = 3.0
                            "kn3"       = 3.0
                            "rat1"      = 2.5
                            "rat2"      = 1.5
                            "rat3"      = 2.0
                            "thr1"      = -17.0
                            "thr2"      = -14.5
                            "thr3"      = -16.5
                            "mak1"      = 2.0
                            "mak2"      = 1.0
                            "mak3"      = 1.0
                            "stereodet" = 1.0
                        }
                    }
                    {
                        type  = lv2
                        name  = maximizer
                        plugin = "urn:zamaudio:ZaMaximX2"
                        control = {
                            "gain"   = 12.0
                            "thresh" = -0.3
                            "rel"    = 25.0
                        }
                    }
                ]
                links = [
                    { output = "eq:outL"                    input = "multicomp:lv2_audio_in_1" }
                    { output = "eq:outR"                    input = "multicomp:lv2_audio_in_2" }
                    { output = "multicomp:lv2_audio_out_1"  input = "maximizer:lv2_audio_in_1" }
                    { output = "multicomp:lv2_audio_out_2"  input = "maximizer:lv2_audio_in_2" }
                ]
            }
            capture.props = {
                node.name = "volume-boost-capture"
                media.class = Audio/Sink
                filter.smart = true
                filter.smart.name = "volume-boost"
                filter.smart.target = { node.name = "alsa_output.pci-0000_09_00.6.analog-stereo" }
            }
            playback.props = {
                node.name = "volume-boost-playback"
                node.passive = true
            }
        }
    }
]
